//======================================================
// Source code generated by jvider v1.8.1 UNREGISTERED version.
// http://www.jvider.com/
//======================================================
import javax.swing.JFrame;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.JPanel;
import javax.swing.BorderFactory;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import javax.swing.JTable;
import javax.swing.JButton;
import javax.swing.JTextField;
import javax.swing.JLabel;
/**
 * @author  Administrator
 * @created January 15, 2017
 */
public class GUI extends JFrame 
{
static GUI theGUI;

JPanel pnPanel0;
JTable tbFundementals;
JButton btSearch;
JTextField tfInput;
JLabel lbFundementals;
JTextField tfCurrentPrice;
JTextField tfTicker;
JTextField tfText4;
JLabel lbPredictedPrice;
JTextField tfName;
/**
 */
public static void main( String args[] ) 
{
   try 
   {
      UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
   }
   catch ( ClassNotFoundException e ) 
   {
   }
   catch ( InstantiationException e ) 
   {
   }
   catch ( IllegalAccessException e ) 
   {
   }
   catch ( UnsupportedLookAndFeelException e ) 
   {
   }
   theGUI = new GUI();
} 

/**
 */
public GUI() 
{
   super( "TITLE" );

   pnPanel0 = new JPanel();
   GridBagLayout gbPanel0 = new GridBagLayout();
   GridBagConstraints gbcPanel0 = new GridBagConstraints();
   pnPanel0.setLayout( gbPanel0 );

   String [][]dataFundementals = new String[][] { new String[] {"Voume", "21"}, 
                                                new String[] {"PE Ratio", "22"}, 
                                                new String[] {"Earnings per share", 
                                                "23"}, 
                                                new String[] {"52 Wk low", ""}, 
                                                new String[] {"52 Wk high", ""}, 
                                                new String[] {"Today's low", ""}, 
                                                new String[] {"Today's high", ""}, 
                                                new String[] {"Market cap", ""}, 
                                                new String[] {"Short ratio", ""}, 
                                                new String[] {"Previous close", ""}, 
                                                new String[] {"Exchange", ""} };
   String []colsFundementals = new String[] { "", "" };
   tbFundementals = new JTable( dataFundementals, colsFundementals );
   gbcPanel0.gridx = 1;
   gbcPanel0.gridy = 6;
   gbcPanel0.gridwidth = 10;
   gbcPanel0.gridheight = 8;
   gbcPanel0.fill = GridBagConstraints.BOTH;
   gbcPanel0.weightx = 1;
   gbcPanel0.weighty = 1;
   gbcPanel0.anchor = GridBagConstraints.NORTH;
   gbPanel0.setConstraints( tbFundementals, gbcPanel0 );
   pnPanel0.add( tbFundementals );

   btSearch = new JButton( "Search"  );
   gbcPanel0.gridx = 13;
   gbcPanel0.gridy = 13;
   gbcPanel0.gridwidth = 5;
   gbcPanel0.gridheight = 1;
   gbcPanel0.fill = GridBagConstraints.BOTH;
   gbcPanel0.weightx = 1;
   gbcPanel0.weighty = 0;
   gbcPanel0.anchor = GridBagConstraints.NORTH;
   gbPanel0.setConstraints( btSearch, gbcPanel0 );
   pnPanel0.add( btSearch );

   tfInput = new JTextField( );
   gbcPanel0.gridx = 13;
   gbcPanel0.gridy = 11;
   gbcPanel0.gridwidth = 5;
   gbcPanel0.gridheight = 1;
   gbcPanel0.fill = GridBagConstraints.BOTH;
   gbcPanel0.weightx = 1;
   gbcPanel0.weighty = 0;
   gbcPanel0.anchor = GridBagConstraints.NORTH;
   gbPanel0.setConstraints( tfInput, gbcPanel0 );
   pnPanel0.add( tfInput );

   lbFundementals = new JLabel( "Fundementals"  );
   gbcPanel0.gridx = 1;
   gbcPanel0.gridy = 5;
   gbcPanel0.gridwidth = 10;
   gbcPanel0.gridheight = 1;
   gbcPanel0.fill = GridBagConstraints.BOTH;
   gbcPanel0.weightx = 1;
   gbcPanel0.weighty = 1;
   gbcPanel0.anchor = GridBagConstraints.NORTH;
   gbPanel0.setConstraints( lbFundementals, gbcPanel0 );
   pnPanel0.add( lbFundementals );

   tfCurrentPrice = new JTextField( );
   gbcPanel0.gridx = 13;
   gbcPanel0.gridy = 4;
   gbcPanel0.gridwidth = 5;
   gbcPanel0.gridheight = 2;
   gbcPanel0.fill = GridBagConstraints.BOTH;
   gbcPanel0.weightx = 1;
   gbcPanel0.weighty = 0;
   gbcPanel0.anchor = GridBagConstraints.NORTH;
   gbPanel0.setConstraints( tfCurrentPrice, gbcPanel0 );
   pnPanel0.add( tfCurrentPrice );

   tfTicker = new JTextField( );
   gbcPanel0.gridx = 1;
   gbcPanel0.gridy = 1;
   gbcPanel0.gridwidth = 9;
   gbcPanel0.gridheight = 3;
   gbcPanel0.fill = GridBagConstraints.BOTH;
   gbcPanel0.weightx = 1;
   gbcPanel0.weighty = 0;
   gbcPanel0.anchor = GridBagConstraints.NORTH;
   gbPanel0.setConstraints( tfTicker, gbcPanel0 );
   pnPanel0.add( tfTicker );

   tfText4 = new JTextField( );
   gbcPanel0.gridx = 13;
   gbcPanel0.gridy = 8;
   gbcPanel0.gridwidth = 5;
   gbcPanel0.gridheight = 2;
   gbcPanel0.fill = GridBagConstraints.BOTH;
   gbcPanel0.weightx = 1;
   gbcPanel0.weighty = 0;
   gbcPanel0.anchor = GridBagConstraints.NORTH;
   gbPanel0.setConstraints( tfText4, gbcPanel0 );
   pnPanel0.add( tfText4 );

   lbPredictedPrice = new JLabel( "Predicted Price"  );
   gbcPanel0.gridx = 14;
   gbcPanel0.gridy = 7;
   gbcPanel0.gridwidth = 3;
   gbcPanel0.gridheight = 1;
   gbcPanel0.fill = GridBagConstraints.BOTH;
   gbcPanel0.weightx = 1;
   gbcPanel0.weighty = 1;
   gbcPanel0.anchor = GridBagConstraints.NORTH;
   gbPanel0.setConstraints( lbPredictedPrice, gbcPanel0 );
   pnPanel0.add( lbPredictedPrice );

   tfName = new JTextField( );
   gbcPanel0.gridx = 13;
   gbcPanel0.gridy = 1;
   gbcPanel0.gridwidth = 5;
   gbcPanel0.gridheight = 2;
   gbcPanel0.fill = GridBagConstraints.BOTH;
   gbcPanel0.weightx = 1;
   gbcPanel0.weighty = 0;
   gbcPanel0.anchor = GridBagConstraints.NORTH;
   gbPanel0.setConstraints( tfName, gbcPanel0 );
   pnPanel0.add( tfName );

   setDefaultCloseOperation( EXIT_ON_CLOSE );

   setContentPane( pnPanel0 );
   pack();
   setVisible( true );
} 
} 
